# Generated by Django 6.0.4 on 2026-05-20 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('umas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(choices=[('Sapporo', 'Sapporo'), ('Hakodate', 'Hakodate'), ('Fukushima', 'Fukushima'), ('Niigata', 'Niigata'), ('Tokyo', 'Tokyo'), ('Nakayama', 'Nakayama'), ('Kyoto', 'Kyoto'), ('Hanshin', 'Hanshin'), ('Kokura', 'Kokura'), ('Oi', 'Oi')], default='Tokyo', max_length=20)),
                ('direction', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('straight', 'Straight')], default='right', max_length=10)),
                ('distance', models.PositiveIntegerField()),
                ('distance_type', models.CharField(choices=[('sprint', 'Sprint'), ('mile', 'Mile'), ('medium', 'Medium'), ('long', 'Long')], default='sprint', max_length=10)),
                ('track', models.CharField(choices=[('dirt', 'Dirt'), ('turf', 'Turf')], default='turf', max_length=20)),
                ('grade', models.CharField(choices=[('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('OP', 'Open'), ('Pre-OP', 'Pre-Open')], default='OP', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=20)),
                ('track_condition', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_races', to='umas.uma')),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='races.race')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_races', to='umas.uma')),
                ('win', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_races', to='umas.uma')),
            ],
        ),
        migrations.CreateModel(
            name='RaceBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umas.uma')),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.raceevent')),
            ],
        ),
        migrations.CreateModel(
            name='RaceParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.PositiveIntegerField()),
                ('favorite_to_win', models.PositiveIntegerField()),
                ('mood', models.CharField(max_length=20)),
                ('race_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.raceevent')),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umas.uma')),
            ],
        ),
        migrations.AddField(
            model_name='raceevent',
            name='uma_participants',
            field=models.ManyToManyField(through='races.RaceParticipation', to='umas.uma'),
        ),
    ]
