# Generated by Django 6.0.4 on 2026-05-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racebets',
            name='odds',
        ),
        migrations.AddField(
            model_name='raceparticipation',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
