# Generated by Django 6.0.4 on 2026-04-29 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='UmaSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('SPD', 'Speed'), ('PAS', 'Passive'), ('RCV', 'Recovery'), ('DBF', 'Debuff')], default='SPD', max_length=3)),
                ('rarity', models.CharField(choices=[('NRM', 'Normal'), ('R', 'Rare'), ('UNQ', 'Unique')], default='NRM', max_length=3)),
                ('uma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umas.uma')),
            ],
        ),
        migrations.CreateModel(
            name='UmaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField()),
                ('stamina', models.PositiveSmallIntegerField()),
                ('power', models.PositiveSmallIntegerField()),
                ('guts', models.PositiveSmallIntegerField()),
                ('wit', models.PositiveSmallIntegerField()),
                ('uma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='umas.uma')),
            ],
        ),
    ]
